name: Build AmneziawgOpenwrt

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Free disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo apt clean
        df -h

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
          gettext git libncurses-dev libssl-dev python3-distutils-extra \
          python3-setuptools rsync unzip zlib1g-dev file wget
        
    - name: Clone OpenWrt
      run: |
        git clone https://git.openwrt.org/openwrt/openwrt.git
        cd openwrt
        git checkout v24.10.2
        
    - name: Clone AmneziawgOpenwrt
      run: |
        git clone https://github.com/amnezia-vpn/amneziawg-openwrt.git package/amneziawg

    - name: Update feeds
      working-directory: openwrt
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure build
      working-directory: openwrt
      run: |
        cat > .config <<'EOF'
        CONFIG_TARGET_rockchip=y
        CONFIG_TARGET_rockchip_armv8=y
        CONFIG_TARGET_rockchip_armv8_DEVICE_friendlyarm_nanopi-r4s=y
        CONFIG_PACKAGE_amneziawg=y
        CONFIG_PACKAGE_kmod-amneziawg=y
        EOF
        make defconfig

    - name: Build package
      working-directory: openwrt
      run: make package/amneziawg/compile -j$(nproc) V=s

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: amneziawg-packages
        path: openwrt/bin/packages/aarch64_generic/base/
        retention-days: 5

    - name: Upload logs on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: build-logs
        path: |
          openwrt/logs/
          openwrt/.config
        retention-days: 5
